// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnHetBmVP0TIFNU49YfEtkl4_jjU-DgZw',
    appId: '1:353537685218:web:a760c9fddaff31a816d0bb',
    messagingSenderId: '353537685218',
    projectId: 'arvia-991',
    authDomain: 'arvia-991.firebaseapp.com',
    storageBucket: 'arvia-991.firebasestorage.app',
    measurementId: 'G-CY6WFSQZ4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARL1-cHmwaLBcdi_4w0ARVzR9CzsJRHJ4',
    appId: '1:353537685218:android:838e465bfe3870ce16d0bb',
    messagingSenderId: '353537685218',
    projectId: 'arvia-991',
    storageBucket: 'arvia-991.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwRTEx6SVtgPHnb7JwVv0C-F0Ho-VEZhM',
    appId: '1:353537685218:ios:4b2b3a5f40ccce5d16d0bb',
    messagingSenderId: '353537685218',
    projectId: 'arvia-991',
    storageBucket: 'arvia-991.firebasestorage.app',
    iosBundleId: 'com.begginers.soc25.arvia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwRTEx6SVtgPHnb7JwVv0C-F0Ho-VEZhM',
    appId: '1:353537685218:ios:4b2b3a5f40ccce5d16d0bb',
    messagingSenderId: '353537685218',
    projectId: 'arvia-991',
    storageBucket: 'arvia-991.firebasestorage.app',
    iosBundleId: 'com.begginers.soc25.arvia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnHetBmVP0TIFNU49YfEtkl4_jjU-DgZw',
    appId: '1:353537685218:web:017c61160fe57dbc16d0bb',
    messagingSenderId: '353537685218',
    projectId: 'arvia-991',
    authDomain: 'arvia-991.firebaseapp.com',
    storageBucket: 'arvia-991.firebasestorage.app',
    measurementId: 'G-2KY800GBRJ',
  );
}
